on:
  workflow_call:
    inputs:
      build-path:
        required: true
        type: string
      plugin-id:
        required: true
        type: string
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Copy plugin into test vault
      run: |
        cp build/* ./tests/e2e/test-vault/.obsidian/plugins/${{ inputs.plugin-id }}
    - name: Install dependencies 
      run: |
        [ -z $(command -v sudo) ] && apt-get update && apt-get install sudo
        sudo apt-get update
        sudo apt-get install -y jq xdg-utils xvfb
        curled=$(curl -L https://github.com/obsidianmd/obsidian-releases/raw/refs/heads/master/desktop-releases.json | jq .latestVersion | sed s/\"//g)
        curl -Lo obsidian.deb "https://github.com/obsidianmd/obsidian-releases/releases/download/v$curled/obsidian_${curled}_amd64.deb"
        yarn install
        yarn playwright install-deps
        sudo dpkg -i ./obsidian.deb
    - name: Run Tests
      run: |
        export XDG_CONFIG_HOME=$HOME/.config
        yarn run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

